language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sqlite3 qt4-dev-tools

before_script:
  - cd core
  - mkdir build
  - cd build
  - cmake ..

script: make

notifications:
  on_success: change
  on_failure: always
