language: cpp

compiler:
  - gcc
  - clang
addons:
 apt:
  packages:
   - sqlite3
   - qt4-dev-tools


before_install:

before_script:
  - cd core
  - mkdir build
  - cd build
  - cmake ..

script: make

notifications:
  on_success: change
  on_failure: always
